# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db_test:
    image: postgres:13
    restart: always
    container_name: tasks-api-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  db_dev:
    image: postgres:13
    restart: always
    container_name: tasks-api-dev
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
    volumes:
      - ./db/dev:/var/lib/postgresql/data
